[
  {
    "copy-type": "point2point",
    "source-env": "PROD",
    "source-lens-name": "orders_feed_lens",
    "source-lens-uuid": "f75b01ad-19f3-5b63-9994-38d0ff186067",
    "source-adls-location": "abfss://prod-container@datalakestrg.dfs.core.windows.net/point2point/orders_feed_lens",
    "source-format": "parquet",
    "target-adls-location": "abfss://preprod-container@datalakestrg.dfs.core.windows.net/point2point/orders_feed_lens",
    "target-format": "parquet",
    "target-env": "PREPROD",
    "target-clean-up": "append",
    "customfilters": {
      "partitioned_column": "event_date",
      "partition_column_format": "yyyy-MM-dd",
      "masking_columns": [
        "customer_email",
        "customer_phone"
      ]
    }
  }
]