[
  {
    "copy-type": "inplace",
    "source-env": "PROD",
    "source-lens-name": "customer_events_lens",
    "source-lens-uuid": "1ea4300e-7387-561b-a618-fade41532b60",
    "source-adls-location": "abfss://prod-container@datalakestrg.dfs.core.windows.net/inplace/customer_events_lens",
    "source-format": "delta",
    "target-adls-location": "abfss://preprod-container@datalakestrg.dfs.core.windows.net/inplace/customer_events_lens",
    "target-format": "delta",
    "target-env": "PREPROD",
    "target-clean-up": "append",
    "customfilters": {
      "partitioned_column": "event_date",
      "partition_column_format": "yyyy-MM-dd",
      "masking_columns": [
        "customer_email",
        "customer_phone"
      ]
    }
  }
]