[
  {
    "copy-type": "output",
    "source-env": "PREPROD",
    "source-lens-name": "reporting_marts_lens",
    "source-lens-uuid": "3ba75820-42b5-588d-a7ec-dee4d7d6959d",
    "source-adls-location": "abfss://preprod-container@datalakestrg.dfs.core.windows.net/output/reporting_marts_lens",
    "source-format": "delta",
    "target-adls-location": "abfss://dev-container@datalakestrg.dfs.core.windows.net/output/reporting_marts_lens",
    "target-format": "delta",
    "target-env": "DEV",
    "target-clean-up": "overwrite",
    "customfilters": {
      "partitioned_column": "event_date",
      "partition_column_format": "yyyy-MM-dd",
      "masking_columns": []
    }
  },
  {
    "copy-type": "output",
    "source-env": "PREPROD",
    "source-lens-name": "reporting_marts_lens",
    "source-lens-uuid": "3ba75820-42b5-588d-a7ec-dee4d7d6959d",
    "source-adls-location": "abfss://preprod-container@datalakestrg.dfs.core.windows.net/output/reporting_marts_lens",
    "source-format": "delta",
    "target-adls-location": "abfss://dev_env1-container@datalakestrg.dfs.core.windows.net/output/reporting_marts_lens",
    "target-format": "delta",
    "target-env": "DEV_env1",
    "target-clean-up": "overwrite",
    "customfilters": {
      "partitioned_column": "event_date",
      "partition_column_format": "yyyy-MM-dd",
      "masking_columns": []
    }
  },
  {
    "copy-type": "output",
    "source-env": "PREPROD",
    "source-lens-name": "reporting_marts_lens",
    "source-lens-uuid": "3ba75820-42b5-588d-a7ec-dee4d7d6959d",
    "source-adls-location": "abfss://preprod-container@datalakestrg.dfs.core.windows.net/output/reporting_marts_lens",
    "source-format": "delta",
    "target-adls-location": "abfss://dev_env2-container@datalakestrg.dfs.core.windows.net/output/reporting_marts_lens",
    "target-format": "delta",
    "target-env": "DEV_env2",
    "target-clean-up": "overwrite",
    "customfilters": {
      "partitioned_column": "event_date",
      "partition_column_format": "yyyy-MM-dd",
      "masking_columns": []
    }
  },
  {
    "copy-type": "output",
    "source-env": "PREPROD",
    "source-lens-name": "reporting_marts_lens",
    "source-lens-uuid": "3ba75820-42b5-588d-a7ec-dee4d7d6959d",
    "source-adls-location": "abfss://preprod-container@datalakestrg.dfs.core.windows.net/output/reporting_marts_lens",
    "source-format": "delta",
    "target-adls-location": "abfss://dev_env3-container@datalakestrg.dfs.core.windows.net/output/reporting_marts_lens",
    "target-format": "delta",
    "target-env": "DEV_env3",
    "target-clean-up": "overwrite",
    "customfilters": {
      "partitioned_column": "event_date",
      "partition_column_format": "yyyy-MM-dd",
      "masking_columns": []
    }
  },
  {
    "copy-type": "output",
    "source-env": "PREPROD",
    "source-lens-name": "reporting_marts_lens",
    "source-lens-uuid": "3ba75820-42b5-588d-a7ec-dee4d7d6959d",
    "source-adls-location": "abfss://preprod-container@datalakestrg.dfs.core.windows.net/output/reporting_marts_lens",
    "source-format": "delta",
    "target-adls-location": "abfss://dev_env4-container@datalakestrg.dfs.core.windows.net/output/reporting_marts_lens",
    "target-format": "delta",
    "target-env": "DEV_env4",
    "target-clean-up": "overwrite",
    "customfilters": {
      "partitioned_column": "event_date",
      "partition_column_format": "yyyy-MM-dd",
      "masking_columns": []
    }
  }
]