[
  {
    "copy-type": "output",
    "source-env": "PROD",
    "source-lens-name": "reporting_marts_lens",
    "source-lens-uuid": "44c71d99-f773-559d-b4fb-4346b638fed0",
    "source-adls-location": "abfss://prod-container@datalakestrg.dfs.core.windows.net/output/reporting_marts_lens",
    "source-format": "delta",
    "target-adls-location": "abfss://preprod-container@datalakestrg.dfs.core.windows.net/output/reporting_marts_lens",
    "target-format": "delta",
    "target-env": "PREPROD",
    "target-clean-up": "overwrite",
    "customfilters": {
      "partitioned_column": "event_date",
      "partition_column_format": "yyyy-MM-dd",
      "masking_columns": []
    }
  }
]