apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dcc-prod-preprod
  namespace: data-copy-console
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dcc-prod-preprod
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dcc-preprod-dev
  namespace: data-copy-console
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dcc-preprod-dev
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
